modLoader="javafml"
loaderVersion="1.0"
license="MIT"
showAsResourcePack=false

[[mods]]
    modId="agenta"
    version="1.6.2"
    displayName="Agenta"
    logoFile="agenta.png"
    authors="Hanro50"
    description='''
    A skin and sound fix for legacy version of minecraft
    '''